POST http://localhost:8080/wsec1e1/ HTTP/1.1
Content-Type: text/xml; charset=utf-8
SOAPAction: ""

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:exam="http://example.com/your-namespace">
   <soapenv:Header/>
   <soapenv:Body>
      <exam:YourRequestElementName>
         <dayOfWeek>lunes</dayOfWeek>
      </exam:YourRequestElementName>
   </soapenv:Body>
</soapenv:Envelope>
